import time
'''
print("W", end='')
time.sleep(0.5)
print("e", end='')
time.sleep(0.5)
print("l", end='')
time.sleep(0.5)
print("c", end='')
time.sleep(0.5)
print("o", end='')
time.sleep(0.5)
print("m", end='')
time.sleep(0.5)
print("e", end='')
time.sleep(0.5)
print(",", end='')
time.sleep(0.5)
print(" ", end='')
time.sleep(0.5)
print("t", end='')
time.sleep(0.5)
print("h", end='')
time.sleep(0.5)
print("i", end='')
time.sleep(0.5)
print("s", end='')
time.sleep(0.5)
'''
def slowPrint(text, inteval):
    for s in text:
        print(s, end='')
        time.sleep(inteval)
    print('')

slowPrint("Welcome, this is how you get into your hatchery, type Hatchery, or hatchery.", 0.1)
slowPrint("If you want to hatch a dragon, then type hatch, or type Hatch and if you don't have a dragon inside of your hatchery then we will tell you.", 0.1)
slowPrint("To hatch a dragon type swipe or Swipe. We will tell you what type, powers, name and many others.", 0.1)
slowPrint("To upgrade your hatchery type upgrade of Upgrade. We will tell you the cost of the upgarde and if you have enough to do it. And we will tell you want the upgrade will do.", 0.1)
slowPrint("")